- name: External 1
  debug:
    msg: External 1

- name: External 2
  debug:
    msg:
      - count {{ item }}
      - hello {{ username }}
      - main item {{ data }}
  loop: "{{ range(1, 3, 1)|list }}"

- name: External 3
  debug:
    msg: External 3
