---
- name: testing roles
  hosts: servera.lab.example.com
  gather_facts: true
  roles:
    - simple
    
    - role: simple
      public_username: Einstein
    
    - role: simple
      public_username: Albert
  pre_tasks:
    - name: Before
      debug:
        msg: Before
  tasks:
    - name: After
      debug:
        msg: After
