- name: play1
  hosts: servera
  tasks:
    - name: get file stats
      stat:
        path: /tmp/dummy
      register: stat_result
          
    - name: exit if destination is not a directory
      fail:
        msg: /tmp/dummy is not a directory
      when:
        - stat_result.stat.exists
        - not stat_result.stat.isdir
      ignore_errors: true
          
    - name: sync dir contents
      synchronize:
        src: files/my_facts.fact
        dest: /etc/ansible/facts.d/
      become: true
