- name: Test First playbook
  hosts: servera
  tasks:
    - name: Task 1
      debug:
        msg: Task 1
          
    - name: create a simple text file
      copy:
        content: "Hello World"
        dest: '/tmp/dummy'
          
    - name: Task 3
      command: date
      register: whatever

    - debug:
        var: whatever
